# https://gitlab.com/gitlab-org/gitlab-foss/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: docker-registry.ripe.net/swe/gitlab-ci/gradle-buildenv:jdk-11


stages:
  - build
  - test
  - qa
  - package
  - deploy

include:
  # Run pipeline on main branch, merge requests, tags.
  # this is equivalent to `workflow.rules:` that set this up.
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  # Use gitlab security scanning
  - template: Dependency-Scanning.gitlab-ci.yml
  # Whitesource
  - project: 'swe/gitlab-ci'
    file: '/templates/whitesource-scanning.yml'

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  WHITESOURCE_PRODUCT: "ba-shared-teams"
  DEBIAN_FRONTEND: noninteractive
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle/"
  GRADLE_OPTS: "-Dorg.gradle.caching=true -Dorg.gradle.parallel=true -Dorg.gradle.daemon=false"
  TERM: dumb

  # org.gradle.daemon: should gradle daemon be used?
  # org.gradle.caching: should gradle build cache be used?
  # org.gradle.parallel: run parallelizable tasks in parallel?
  # org.gradle.logging.level=info: logs artifact downloads

# Cache per repository (not shared between forks?).
cache: &global_cache
  key: one-key-for-all
  # In general, only pull the cache. pull-push in the stage that gathers all
  # artifacts.
  policy: pull
  paths:
    - "${CI_PROJECT_DIR}/.gradle/caches"
    - "${CI_PROJECT_DIR}/.gradle/wrappers"

build:
  stage: build
  cache:
    <<: *global_cache
    policy: pull-push
  # Diagram of gradle tasks and their dependencies: https://docs.gradle.org/current/userguide/img/javaPluginTasks.png
  script:
    # build all classes, do not run tests or create jar.
    - gradle clean testClasses
  # Cache the build artifacts in specific paths
  artifacts:
    paths:
      - "build"
    expire_in: 4 weeks

test:
  stage: test
  dependencies:
    - build
  script:
    - gradle check
    - cat build/reports/jacoco/test/html/index.html
  artifacts:
    when: on_failure
    paths:
      - build/reports/
    expire_in: 4 days
    reports:
      junit:
        - build/test-results/test/*.xml

# Use artifacts of test step, which creates coverage reports
sonarqube:
  stage: qa
  dependencies:
    - test
  variables:
    GIT_DEPTH: 0
  script:
    - gradle -Dsonar.host.url="${SONAR_HOST_URL}" -Dsonar.login="${SONAR_TOKEN}" -Dsonar.projectKey=rpki-monitoring check sonarqube
  allow_failure: true
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


# All the package stages only require the test job, so whitesource scanning can
# progress in parallel since this takes up to ten minutes.
build:dev:
  stage: package
  rules:
    - when: manual
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - gradle jib --image=$CI_REGISTRY_IMAGE:dev

build:prepdev:
  stage: package
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - gradle jib --image=$CI_REGISTRY_IMAGE
    - gradle jib --image=$CI_REGISTRY_IMAGE:master
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:production:
  stage: package
  script:
    - if [[ "$CI_COMMIT_TAG" =~ ^rpki-monitoring-.* ]]; then echo "Correct tag"; else exit 1; fi
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - gradle jib --image=$CI_REGISTRY_IMAGE:$(echo $CI_COMMIT_TAG | sed -e's/rpki-monitoring-//')
    - gradle jib --image=$CI_REGISTRY_IMAGE:production
  rules:
    - if: $CI_COMMIT_TAG

.deploy_template: &deploy_template
  stage: deploy
  image: docker-registry.ripe.net/swe/gitlab-ci/debian-deployenv
  script:
    - if [ -z "${SALT_DEPLOY_TARGET}" ]; then echo "set SALT_DEPLOY_TARGET"; exit 2; fi;
    - echo "SALT_DEPLOY_TARGET=${SALT_DEPLOY_TARGET}"
    - echo "Logging into salt-api"
    - >
      curl -f -ik https://salt.ripe.net:8000/login \
        -c ~/cookies.txt \
        -H 'Accept: application/x-yaml' \
        -d username='rpkideploy' \
        -d password="$RPKIDEPLOY_PASS" \
        -d eauth='pam'

    # Run `docker.container_up` state because container is not
    # behind f5: No reason to use that logic
    - echo "Updating containers via salt on $SALT_DEPLOY_TARGET"
    - >
      curl -f -D "/dev/stderr" -k https://salt.ripe.net:8000 \
        -b ~/cookies.txt \
        -H 'Content-type: application/json' -d"
            [{
              \"timeout\": 120,
              \"failhard\": \"True\",
              \"client\": \"local_batch\",
              \"batch-size\": \"25%\",
              \"saltenv\": \"base\",
              \"fun\": \"state.apply\",
              \"tgt_type\": \"glob\",
              \"tgt\": \"$SALT_DEPLOY_TARGET\",
              \"arg\": [\"docker.container_up\"],
              \"kwarg\": {
                \"pillar\": {
                  \"vars\": {
                    \"container\": \"rpki-monitoring\",
                    \"health_endpoint\": \"http://127.0.0.1:9090/actuator/info\",
                    \"drain_time\": \"30\"
                  }
                }
              }
            }]
            "

deploy:dev:
  <<: *deploy_template
  environment:
    name: dev
    url: http://uncore-1.rpki.dev.ripe.net:9090
  rules:
    - when: manual

deploy:prepdev:
  <<: *deploy_template
  stage: deploy
  environment:
    name: prepdev
    url: https://uncore.rpki.prepdev.ripe.net
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:production:
  <<: *deploy_template
  stage: deploy
  environment:
    name: production
    url: https://uncore.rpki.ripe.net
  rules:
    - if: $CI_COMMIT_TAG
