# Spring Boot always loads `application.yaml`. Afterwards the settings are loaded for the active profile. These are
# merged: By default, `application.yaml` is loaded and `application-default.yaml` extends it.
#
# The default for naming is 'lower-case kebab format' such as 'my.proper-tyname=acme' as recommended in [0].
# [0]: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-relaxed-binding
#
spring:
  main.banner-mode: off
  output.ansi.enabled: ALWAYS
  application.name: rpki-monitoring


rrdp:
  main-url: https://rrdp.prepdev.ripe.net
  interval: 5M
  other-urls: {}

rsync:
  # *without* the trailing slash
  main-url: rsync://rpki.prepdev.ripe.net
  timeout: 30
  interval: 5M
  base-directory: /tmp/rsync/
  other-urls:
    new_rsync: rsync://rpki2.prepdev.ripe.net

server:
  port: 9090
  shutdown: graceful

rpkimonitor:
  version: "@gitVersion@"
  internal-api-key-header: "ncc-internal-api-key"

core:
  url: https://ba-apps.prepdev.ripe.net/certification/
  api-key: BAD-TEST-D2Shtf2n5Bwh02P7
  interval: 1m
  initial-delay: 10s

published-objects:
  # The interval at which a full diff on all repositories is collected. Incidentally
  # this _also_ is the interval at which the core repository is tracked.
  full-diff-interval: 5M

logging:
  level:
    web: INFO
    net.ripe.rpki: DEBUG

# Enable prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health

---
spring:
  profiles: local

rrdp:
  url: http://localhost
  interval: 5M

rsync:
  # *without* the trailing slash
  main-url: rsync://localhost:10873
  timeout: 30
  interval: 5M

core:
  url: http://localhost:8080/certification/
  api-key: BAD-TEST-D2Shtf2n5Bwh02P7

---
spring:
  profiles: prepdev

rrdp:
  main-url: https://rrdp.prepdev.ripe.net
  interval: 5M
  other-urls:
    publish: https://publish.rpki.prepdev.ripe.net

rsync:
  # *without* a trailing slash
  main-url: rsync://rpki.prepdev.ripe.net
  timeout: 30
  interval: 5M
  base-directory: /tmp/rsync/
  other-urls:
    new_rsync: rsync://rpki2.prepdev.ripe.net

core:
  url: https://ba-apps.prepdev.ripe.net/certification/

---
spring:
  profiles: production

rrdp:
  main-url: https://rrdp.ripe.net
  interval: 5M
  other-urls:
    publish: https://rrdp.int.ripe.net

rsync:
  # *without* the trailing slash
  main-url: rsync://rpki.ripe.net
  base-directory: /tmp/rsync/
  timeout: 30
  interval: 5M
  other-urls:
    new_rsync: rsync://rpki2.ripe.net

core:
  url: https://ba-apps.ripe.net/certification/
