# Spring Boot always loads `application.yaml`. Afterwards the settings are loaded for the active profile. These are
# merged: By default, `application.yaml` is loaded and `application-default.yaml` extends it.
#
# The default for naming is 'lower-case kebab format' such as 'my.proper-tyname=acme' as recommended in [0].
# [0]: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-relaxed-binding
#
spring:
  main.banner-mode: off
  output.ansi.enabled: ALWAYS
  application.name: rpki-monitoring


rrdp:
  interval: 5M
  targets:
    - name: main
      notification-url: https://rrdp.prepdev.ripe.net/notification.xml

rsync:
  repository-url: rsync://rpki.prepdev.ripe.net
  timeout: 30
  interval: 5M
  base-directory: /tmp/rsync/
  targets:
    - name: rsync
      url: rsync://rpki.prepdev.ripe.net

server:
  port: 9090
  shutdown: graceful

rpkimonitor:
  version: "@gitVersion@"
  internal-api-key-header: "ncc-internal-api-key"

core:
  url: https://core.rpki.prepdev.ripe.net/certification/
  api-key: BAD-TEST-D2Shtf2n5Bwh02P7
  interval: 1m
  initial-delay: 10s

published-objects:
  # The interval at which a full diff on all repositories is collected. Incidentally
  # this _also_ is the interval at which the core repository is tracked.
  full-diff-interval: 5M

logging:
  level:
    web: INFO
    net.ripe.rpki: DEBUG

# Enable prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health

---
spring:
  profiles: local

rrdp:
  interval: 5M
  targets:
    - name: main
      notification-url: https://rrdp.int.ripe.net/notification.xml
      override-hostname: rrdp.int.ripe.net

rsync:
  # *without* the trailing slash
  main-url: rsync://localhost:10873
  timeout: 30
  interval: 5M

core:
  url: http://localhost:8080/certification/
  api-key: BAD-TEST-D2Shtf2n5Bwh02P7

---
spring:
  profiles: prepdev

rrdp:
  interval: 5M
  targets:
    - name: main
      notification-url: https://rrdp.prepdev.ripe.net/notification.xml
    - name: publish
      notification-url: https://publish.rpki.prepdev.ripe.net/notification.xml
    - name: i3d
      notification-url: https://rrdp.prepdev.ripe.net/notification.xml
      connect-to:
        rrdp.prepdev.ripe.net: ripe-test.cdn.i3d.net
    - name: cloudflare
      notification-url: https://rrdp.prepdev.ripe.net/notification.xml
      connect-to:
        rrdp.prepdev.ripe.net: rrdp.prepdev.ripe.net.cdn.cloudflare.net

rsync:
  repository-url: rsync://rpki.prepdev.ripe.net
  timeout: 30
  interval: 5M
  base-directory: /tmp/rsync/
  targets:
    - name: rsync
      url: rsync://rpki.prepdev.ripe.net

core:
  url: https://core.rpki.prepdev.ripe.net/certification/

---
spring:
  profiles: production

rrdp:
  interval: 5M
  targets:
    - name: main
      notification-url: https://rrdp.ripe.net/notification.xml
    - name: publish
      notification-url: https://rrdp.int.ripe.net/notification.xml
      override-hostname: rrdp.int.ripe.net
    - name: i3d
      notification-url: https://rrdp.ripe.net/notification.xml
      connect-to:
        rrdp.prepdev.ripe.net: override-hostname: ripe.cdn.i3d.net
    - name: cloudflare
      notification-url: https://rrdp.ripe.net/notification.xml
      connect-to:
        rrdp.ripe.net: rrdp.ripe.net.cdn.cloudflare.net
    - name: beanstalk
      notification-url: http://rrdp.ripe.net/notification.xml
      connect-to:
        rrdp.ripe.net: publicationserver-prod-1.eu-west-1.elasticbeanstalk.com

rsync:
  repository-url: rsync://rpki.ripe.net
  base-directory: /tmp/rsync/
  timeout: 30
  interval: 5M
  targets:
    - name: rsync
      url: rsync://rpki.ripe.net

core:
  url: https://core.rpki.ripe.net/certification/
