# Spring Boot always loads `application.yaml`. Afterwards the settings are loaded for the active profile. These are
# merged: By default, `application.yaml` is loaded and `application-default.yaml` extends it.
#
# The default for naming is 'lower-case kebab format' such as 'my.proper-tyname=acme' as recommended in [0].
# [0]: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-relaxed-binding
#
spring:
  main.banner-mode: off
  output.ansi.enabled: ALWAYS
  application.name: rpki-monitoring
  # Affects maximum HTTP response size
  codec.max-in-memory-size: 1GB

# The number of collectors running in parallel has a huge influence on heap usage.
collector.threads: 2

rrdp:
  interval: 5M
  targets:
    - name: main
      notification-url: https://rrdp.prepdev.ripe.net/notification.xml

rsync:
  repository-url: rsync://rpki.prepdev.ripe.net
  directories:
    - ta
    - repository
  timeout: 30
  interval: 5M
  fetch-ta: true
  base-directory: /tmp/rsync/
  targets:
    - name: rsync
      url: rsync://rpki.prepdev.ripe.net

certificate.analysis:
  enabled: true
  root-certificate-url: rsync://rpki.prepdev.ripe.net/ta/RIPE-NCC-TA-TEST.cer
  ignored-overlaps: []

expiry:
  # repository tags for which the regex matching is performed.
  # not present -> all. empty list -> none. specific values -> only these.
  track-tags:
    - main
  match:
    - regex: 'rsync://.*/repository/[^/]+'
      threshold: 21D
      labels:
        file_description: 'products of offline CA'
    - regex: 'rsync://.*/ta/.*'
      threshold: 180D
      labels:
        file_description: 'TA certificate'
    - regex: 'rsync://.*/repository/aca/.*'
      threshold: 15H
      labels:
        file_description: 'production CA manifest & crl'

server:
  port: 9090
  shutdown: graceful

rpkimonitor:
  internal-api-key-header: "ncc-internal-api-key"

core:
  enable: true
  url: https://core.rpki.prepdev.ripe.net/certification/
  api-key: BAD-TEST-D2Shtf2n5Bwh02P7
  interval: 1m
  initial-delay: 10s

published-objects:
  # The interval at which a full diff on all repositories is collected. Incidentally
  # this _also_ is the interval at which the core repository is tracked.
  full-diff-interval: 5M

logging:
  level:
    web: INFO
    net.ripe.rpki: DEBUG

management:
  tracing.enabled: false
  otlp.metrics.export.enabled: false
  # 100% sample rate
  tracing.sampling.probability: 1.0
  # Enable prometheus endpoint
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health

otel:
  traces.exporter: otlp
  metrics.exporter: none
  logs.exporter: otlp
# Set OTEL_RESOURCE_ATTRIBUTES and other OTLP env vars via environment variables,
#  export MANAGEMENT_OTLP_TRACING_ENDPOINT=https://apm.prepdev.ripe.net:8200/v1/traces
#  export MANAGEMENT_OTLP_TRACING_HEADERS_Authorization="Bearer base64=="
#  export OTEL_EXPORTER_OTLP_HEADERS="Authorization=Bearer base64=="
#  export OTEL_RESOURCE_ATTRIBUTES=service.name=rpki-monitoring,service.version=main,deployment.environment=prepdev
---
spring.config.activate.on-profile: local

rrdp:
  interval: 5M
  targets:
    - name: main
      notification-url: https://rrdp.ripe.net/notification.xml
      connect-to:
        rrdp.ripe.net: rrdp.int.ripe.net

rsync:
  # *without* the trailing slash
  main-url: rsync://localhost:10873
  directories:
    - ta
    - repository
  timeout: 30
  interval: 5M

core:
  enable: true
  url: http://localhost:8080/certification/
  api-key: BAD-TEST-D2Shtf2n5Bwh02P7

certificate.analysis:
  enabled: true
  root-certificate-url: rsync://rpki.prepdev.ripe.net/ta/RIPE-NCC-TA-TEST.cer
  ignored-overlaps:
    - regex: 'rsync://.*/repository/DEFAULT/[^/]+'
      description: 'intermediate CAs'
---
spring.config.activate.on-profile: prepdev

rrdp:
  interval: 5M
  targets:
    - name: main
      notification-url: https://rrdp.prepdev.ripe.net/notification.xml
    - name: publish
      notification-url: https://rrdp.int.prepdev.ripe.net/notification.xml
      override-hostname: rrdp.int.prepdev.ripe.net
    - name: cloudflare
      notification-url: https://rrdp.prepdev.ripe.net/notification.xml
      connect-to:
        rrdp.prepdev.ripe.net: rrdp.prepdev.ripe.net.cdn.cloudflare.net
    - name: akamai
      notification-url: https://rrdp.prepdev.ripe.net/notification.xml
      connect-to:
        rrdp.prepdev.ripe.net: rrdp.prepdev.ripe.net.akamaized.net

rsync:
  repository-url: rsync://rpki.prepdev.ripe.net
  directories:
    - ta
    - repository
  timeout: 30
  interval: 5M
  base-directory: /tmp/rsync/
  targets:
    - name: rsync
      url: rsync://rsync-1.rpki.prepdev.ripe.net
    - name: rsyncit-1
      url: rsync://rsyncit-1.rpki.prepdev.ripe.net
    - name: rsyncit-2
      url: rsync://rsyncit-2.rpki.prepdev.ripe.net

core:
  enable: true
  url: https://core.rpki.prepdev.ripe.net/certification/

management:
  tracing.enabled: true
---
spring.config.activate.on-profile: production

certificate.analysis:
  enabled: true
  root-certificate-url: rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer

rrdp:
  interval: 5M
  targets:
    - name: main
      notification-url: https://rrdp.ripe.net/notification.xml
    - name: publish
      notification-url: https://rrdp.int.ripe.net/notification.xml
      override-hostname: rrdp.int.ripe.net
    - name: cloudflare
      notification-url: https://rrdp.ripe.net/notification.xml
      connect-to:
        rrdp.ripe.net: rrdp.ripe.net.cdn.cloudflare.net
    - name: akamai
      notification-url: https://rrdp.ripe.net/notification.xml
      connect-to:
        rrdp.ripe.net: rrdp.ripe.net.akamaized.net
    - name: linode
      notification-url: https://publish.linode.rpki.ripe.net/notification.xml
      override-hostname: publish.linode.rpki.ripe.net

rsync:
  repository-url: rsync://rpki.ripe.net
  directories:
    - ta
    - repository
  base-directory: /tmp/rsync/
  timeout: 30
  interval: 5M
  targets:
    - name: rsync
      url: rsync://rpki.ripe.net
    - name: rsyncit-1
      url: rsync://rsyncit-1.rpki.ripe.net
    - name: rsyncit-2
      url: rsync://rsyncit-2.rpki.ripe.net

core:
  enable: true
  url: https://core.rpki.ripe.net/certification/

---
spring.config.activate.on-profile: paas-prepdev

rrdp:
  interval: 5M
  targets:
    - name: main
      notification-url: https://rrdp.paas.rpki.prepdev.ripe.net/notification.xml
    - name: krill-sync
      notification-url: https://rrdp.int.paas.rpki.prepdev.ripe.net/notification.xml
      override-hostname: rrdp.int.paas.rpki.prepdev.ripe.net
    - name: krill-internal
      notification-url: https://internal.paas.rpki.prepdev.ripe.net/notification.xml
      override-hostname: internal.paas.rpki.prepdev.ripe.net

rsync:
  repository-url: rsync://rsync.paas.rpki.prepdev.ripe.net
  directories:
    - repository
  base-directory: /tmp/rsync/
  fetch-ta: false
  timeout: 30
  interval: 5M
  targets:
    - name: rsync
      url: rsync://rsync.paas.rpki.prepdev.ripe.net

core:
  enable: false

certificate.analysis:
  enabled: false

management:
  tracing.enabled: true
---
spring.config.activate.on-profile: paas-production

rrdp:
  interval: 5M
  targets:
    - name: main
      notification-url: https://rrdp.paas.rpki.ripe.net/notification.xml
    - name: krill-sync
      notification-url: https://rrdp.int.paas.rpki.ripe.net/notification.xml
      override-hostname: rrdp.int.paas.rpki.ripe.net
    - name: krill-internal
      notification-url: https://internal.paas.rpki.ripe.net/notification.xml
      override-hostname: internal.paas.rpki.ripe.net
    - name: cloudflare
      notification-url: https://rrdp.paas.rpki.ripe.net/notification.xml
      connect-to:
        rrdp.paas.rpki.ripe.net: rrdp.paas.rpki.ripe.net.cdn.cloudflare.net

rsync:
  repository-url: rsync://rsync.paas.rpki.ripe.net
  directories:
    - repository
  base-directory: /tmp/rsync/
  fetch-ta: false
  timeout: 30
  interval: 5M
  targets:
    - name: rsync
      url: rsync://rsync.paas.rpki.ripe.net

core:
  enable: false

certificate.analysis:
  enabled: false
