# Spring Boot always loads `application.yaml`. Afterwards the settings are loaded for the active profile. These are
# merged: By default, `application.yaml` is loaded and `application-default.yaml` extends it.
#
# The default for naming is 'lower-case kebab format' such as 'my.proper-tyname=acme' as recommended in [0].
# [0]: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-relaxed-binding
#
spring:
  main.banner-mode: off
  output.ansi.enabled: ALWAYS
  application.name: rpki-monitoring


rrdp:
  main-url: https://rrdp.prepdev.ripe.net
  other-urls:
    publish-1: http://publish-1.rpki.prepdev.ripe.net:7788
  interval: 5M

rsync:
  # *without* the trailing slash
  main-url: rsync://rpki.prepdev.ripe.net
  timeout: 30
  interval: 10M
  # disable second rsync url
  other-urls: {}

server:
  port: 9090
  shutdown: graceful

rpkimonitor:
  version: "@gitVersion@"
  internal-api-key-header: "ncc-internal-api-key"

core:
  url: https://ba-apps.prepdev.ripe.net/certification/
  api-key: BAD-TEST-D2Shtf2n5Bwh02P7

logging:
  level:
    web: INFO
    net.ripe.rpki: DEBUG

# Enable prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health

---
spring:
  profiles: local

rrdp:
  url: http://localhost
  interval: 5M

rsync:
  # *without* the trailing slash
  main-url: rsync://localhost:10873
  timeout: 30
  interval: 5M
  other-urls: {}

core:
  url: http://localhost:8080/certification/
  api-key: BAD-TEST-D2Shtf2n5Bwh02P7

---
spring:
  profiles: prepdev

rrdp:
  main-url: https://rrdp.prepdev.ripe.net
  interval: 5M

rsync:
  # *without* a trailing slash
  main-url: rsync://rpki.prepdev.ripe.net
  timeout: 30
  interval: 10M

core:
  url: https://ba-apps.prepdev.ripe.net/certification/

---
spring:
  profiles: production

rrdp:
  main-url: https://rrdp.ripe.net
  interval: 5M
  other-urls: {}

rsync:
  # *without* the trailing slash
  main-url: rsync://rpki.ripe.net
  timeout: 30
  interval: 10M
  # url to the AWS hosted
  other-urls: {}
    # - rsync://pub-server-prod.elasticbeanstalk.com

core:
  url: https://ba-apps.ripe.net/certification/
